version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: arbitrage-bot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-your_redis_password}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-your_redis_password}
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arbitrage-bot
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-your_redis_password}
    restart: unless-stopped

volumes:
  redis_data: